name: Deploy
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: yarn
      - name: Unit tests
        run: yarn test
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      # - name: Add key
      # run: echo "${{secrets.DEPLOY_KEY}}" > deploy_key
      - name: Add to known hosts
        # SSH_HOST is the IP of the digital ocean dropley
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Copy files
        run: rsync -avz ./build/ ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:${{secrets.DEST_FOLDER}}
